set NAMES utf8mb4;

CREATE TABLE checkpoints (
     id BIGINT PRIMARY KEY AUTO_INCREMENT,
     route_id BIGINT NOT NULL,
     name VARCHAR(100) NOT NULL,
     point VARCHAR(50) NOT NULL,
     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

     CONSTRAINT fk_checkpoint_route FOREIGN KEY (route_id)
         REFERENCES routes(id)
         ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;